modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Lykrast/GunsWithoutRoses/issues"
license="MIT License https://github.com/Lykrast/GunsWithoutRoses/blob/master/LICENSE"

[[mods]]
modId="gunswithoutroses"
version="${version}"
displayName="Guns Without Roses"
displayURL="https://www.curseforge.com/minecraft/mc-mods/guns-without-roses"
credits="freesound.org for sounds, Rye for naming the Cherrounds"
authors="Lykrast"
description='''
Adds a few simple Terraria-like guns, and bullets and enchantments to go with them. Does not add roses of any kind.
'''

[[dependencies.turf]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.turf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"