modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Lykrast/GunsWithoutRoses/issues"
license="MIT License https://github.com/Lykrast/GunsWithoutRoses/blob/master/LICENSE"

[[mods]]
modId="gunswithoutroses"
version="${file.jarVersion}"
displayName="Guns Without Roses"
displayURL="https://www.curseforge.com/minecraft/mc-mods/guns-without-roses"
credits="freesound.org for sounds, Rye for naming the Cherrounds"
authors="Lykrast"
description='''
Adds a few simple Terraria-like guns, and bullets and enchantments to go with them. Does not add roses of any kind.
'''

[[dependencies.gunswithoutroses]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunswithoutroses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"